### ISSUE TITLE
library emits malformed User-Agent

### ISSUE THREAD

**Issue by majewsky** [sapcc/elektron#2]
https://github.com/sapcc/elektron/blob/47c09b573f63b9698db822f5fbd9a94898659c8b/lib/elektron/http_client.rb#L28

User-Agent strings may not contain spaces. [[RFC 7230, section 5.5.3]](https://tools.ietf.org/html/rfc7231#section-5.5.3) This should be changed to `elektron/<version-string>`.

**Comment by andypf** [comment]
Good point! Thanks
